application: gaefeedfind
version: 1
runtime: python27
threadsafe: false
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static

# Endpoints handler
- url: /_ah/spi/.*
  script: parser_api.APPLICATION

#- url: /scheduleReport
#  script: main.application
#  login: required
#
#- url: /data
#  script: main.application
#  login: required

# Main page
- url: /.*
  script: main.application
  login: required
  secure: optional

#- url: /
#  static_files: templates/index.html
#  upload: templates/index\.html
#  secure: always
#  login: required
