application: gaefeedfind
version: 1
runtime: python27
threadsafe: false
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static

- url: /scheduleReport
  script: main.application
  login: required

- url: /data
  script: main.application
  login: required

# Main page
- url: /.*
  script: main.application
  login: required
  secure: always
